In [23]:
import pandas as pd
from datasets import load_dataset
df=pd.read_csv('/home/loki/Developer/Python_Data/Datasets/data')

In [24]:
df['total_bedrooms']

0        1283.0
1        1901.0
2         174.0
3         337.0
4         326.0
          ...
16995     394.0
16996     528.0
16997     531.0
16998     552.0
16999     300.0
Name: total_bedrooms, Length: 17000, dtype: float64

In [25]:
df.total_bedrooms

0        1283.0
1        1901.0
2         174.0
3         337.0
4         326.0
          ...
16995     394.0
16996     528.0
16997     531.0
16998     552.0
16999     300.0
Name: total_bedrooms, Length: 17000, dtype: float64

In [26]:
df.total_bedrooms[0]

np.float64(1283.0)

In [27]:
from datasets import load_dataset
dataset=load_dataset('lukebarousse/data_jobs')

In [28]:
df +=dataset['train'].to_pandas()

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           0 non-null      float64
 1   latitude            0 non-null      float64
 2   housing_median_age  0 non-null      float64
 3   total_rooms         0 non-null      float64
 4   total_bedrooms      0 non-null      float64
 5   population          0 non-null      float64
 6   households          0 non-null      float64
 7   median_income       0 non-null      float64
 8   median_house_value  0 non-null      float64
dtypes: float64(9)
memory usage: 1.2 MB

In [30]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df[['total_rooms','total_bedrooms']].iloc[90:100]

    total_rooms  total_bedrooms
90          NaN             NaN
91          NaN             NaN
92          NaN             NaN
93          NaN             NaN
94          NaN             NaN
95          NaN             NaN
96          NaN             NaN
97          NaN             NaN
98          NaN             NaN
99          NaN             NaN

In [32]:
df.iloc[90:100 , 0:3]

    longitude  latitude  housing_median_age
90        NaN       NaN                 NaN
91        NaN       NaN                 NaN
92        NaN       NaN                 NaN
93        NaN       NaN                 NaN
94        NaN       NaN                 NaN
95        NaN       NaN                 NaN
96        NaN       NaN                 NaN
97        NaN       NaN                 NaN
98        NaN       NaN                 NaN
99        NaN       NaN                 NaN

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           0 non-null      float64
 1   latitude            0 non-null      float64
 2   housing_median_age  0 non-null      float64
 3   total_rooms         0 non-null      float64
 4   total_bedrooms      0 non-null      float64
 5   population          0 non-null      float64
 6   households          0 non-null      float64
 7   median_income       0 non-null      float64
 8   median_house_value  0 non-null      float64
dtypes: float64(9)
memory usage: 1.2 MB

In [34]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
len(df)

17000

In [36]:
df.columns()

TypeError: 'Index' object is not callable