In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#load data
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()
df['jon_posted_date']=pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [3]:
def projected_salary(s):
    return s*0.3
df_salary=df[pd.notna(df['salary_year_avg'])].copy()

In [4]:
df_salary['salary_inflanted']=df_salary['salary_year_avg'].apply(projected_salary)

In [7]:
df_salary[['salary_year_avg','salary_inflanted']]

        salary_year_avg  salary_inflanted
28             109500.0           32850.0
77             140000.0           42000.0
92             120000.0           36000.0
100            228222.0           68466.6
109             89000.0           26700.0
...                 ...               ...
785624         139216.0           41764.8
785641         150000.0           45000.0
785648         221875.0           66562.5
785682         157500.0           47250.0
785692         157500.0           47250.0

[22003 rows x 2 columns]

In [8]:
df_salary['s_inflanted']=df_salary['salary_year_avg'].apply(lambda salary: salary*0.3)

In [9]:
df_salary['s_inflanted']

28        32850.0
77        42000.0
92        36000.0
100       68466.6
109       26700.0
           ...
785624    41764.8
785641    45000.0
785648    66562.5
785682    47250.0
785692    47250.0
Name: s_inflanted, Length: 22003, dtype: float64

In [23]:
import ast

job_skill=df[df['job_skills'].notna()]
job_skill['job_skills']=job_skill['job_skills'].apply(ast.literal_eval)

/tmp/ipykernel_3173/2482535770.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  job_skill['job_skills']=job_skill['job_skills'].apply(ast.literal_eval)

In [27]:
job_skill['job_skills']

1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
5                                        [python, sql, gcp]
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 668704, dtype: object

In [31]:
def promoted(row):
    if  "Senior" in row:
        return 1.03*row['salary_year_avg']
    else:
        return 0.3*row['salary_year_avg']

job_skill['promoted_salary']=job_skill.apply(promoted,axis=1)
job_skill

/tmp/ipykernel_3173/781939189.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  job_skill['promoted_salary']=job_skill.apply(promoted,axis=1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,jon_posted_date,promoted_salary
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",2023-01-14 13:18:07,NaN
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",2023-10-10 13:14:55,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"[python, c++, java, matlab, aws, tensorflow, k...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",2023-07-04 13:01:41,NaN
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"[bash, python, oracle, aws, ansible, puppet, j...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",2023-08-07 14:29:36,NaN
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"[python, sql, gcp]","{'cloud': ['gcp'], 'programming': ['python', '...",2023-11-07 14:01:59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"[bash, python, perl, linux, unix, kubernetes, ...","{'os': ['linux', 'unix'], 'other': ['kubernete...",2023-03-13 06:16:16,NaN
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"[sas, sas, sql, excel]","{'analyst_tools': ['sas', 'excel'], 'programmi...",2023-03-12 06:18:18,NaN
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"[powerpoint, excel]","{'analyst_tools': ['powerpoint', 'excel']}",2023-03-12 06:32:36,NaN
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"[python, go, nosql, sql, mongo, shell, mysql, ...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",2023-03-12 06:32:15,NaN
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"[aws, flow]","{'cloud': ['aws'], 'other': ['flow']}",2023-03-13 06:16:31,NaN